-- MySQL Script generated by MySQL Workbench
-- Mon Nov  9 14:39:16 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema HappyApp
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `HappyApp` ;

-- -----------------------------------------------------
-- Schema HappyApp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `HappyApp` DEFAULT CHARACTER SET utf8 ;
USE `HappyApp` ;

-- -----------------------------------------------------
-- Table `HappyApp`.`Restaurant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HappyApp`.`Restaurant` ;

CREATE TABLE IF NOT EXISTS `HappyApp`.`Restaurant` (
  `restname` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(45) NULL,
  PRIMARY KEY (`restname`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HappyApp`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HappyApp`.`User` ;

CREATE TABLE IF NOT EXISTS `HappyApp`.`User` (
  `curtime` DECIMAL(3,1) NOT NULL,
  `curday` VARCHAR(9) NULL,
  PRIMARY KEY (`curtime`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HappyApp`.`Monday`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HappyApp`.`Monday` ;

CREATE TABLE IF NOT EXISTS `HappyApp`.`Monday` (
  `Restaurant_restname` VARCHAR(45) NOT NULL,
  `stime` DECIMAL(3,1) NOT NULL,
  `etime` DECIMAL(3,1) NOT NULL,
  `food` VARCHAR(255) NULL,
  `drink` VARCHAR(255) NULL,
  PRIMARY KEY (`Restaurant_restname`, `stime`, `etime`),
  INDEX `fk_Monday_Restaurant_idx` (`Restaurant_restname` ASC),
  CONSTRAINT `fk_Monday_Restaurant`
    FOREIGN KEY (`Restaurant_restname`)
    REFERENCES `HappyApp`.`Restaurant` (`restname`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HappyApp`.`Tuesday`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HappyApp`.`Tuesday` ;

CREATE TABLE IF NOT EXISTS `HappyApp`.`Tuesday` (
  `Restaurant_restname` VARCHAR(45) NOT NULL,
  `stime` DECIMAL(3,1) NOT NULL,
  `etime` DECIMAL(3,1) NOT NULL,
  `food` VARCHAR(255) NULL,
  `drink` VARCHAR(255) NULL,
  PRIMARY KEY (`Restaurant_restname`, `stime`, `etime`),
  INDEX `fk_Tuesday_Restaurant1_idx` (`Restaurant_restname` ASC),
  CONSTRAINT `fk_Tuesday_Restaurant1`
    FOREIGN KEY (`Restaurant_restname`)
    REFERENCES `HappyApp`.`Restaurant` (`restname`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HappyApp`.`Wednesday`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HappyApp`.`Wednesday` ;

CREATE TABLE IF NOT EXISTS `HappyApp`.`Wednesday` (
  `Restaurant_restname` VARCHAR(45) NOT NULL,
  `stime` DECIMAL(3,1) NOT NULL,
  `etime` DECIMAL(3,1) NOT NULL,
  `food` VARCHAR(255) NULL,
  `drink` VARCHAR(255) NULL,
  PRIMARY KEY (`Restaurant_restname`, `stime`, `etime`),
  INDEX `fk_Wednesday_Restaurant1_idx` (`Restaurant_restname` ASC),
  CONSTRAINT `fk_Wednesday_Restaurant1`
    FOREIGN KEY (`Restaurant_restname`)
    REFERENCES `HappyApp`.`Restaurant` (`restname`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HappyApp`.`Thursday`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HappyApp`.`Thursday` ;

CREATE TABLE IF NOT EXISTS `HappyApp`.`Thursday` (
  `Restaurant_restname` VARCHAR(45) NOT NULL,
  `stime` DECIMAL(3,1) NOT NULL,
  `etime` DECIMAL(3,1) NOT NULL,
  `food` VARCHAR(255) NULL,
  `drink` VARCHAR(255) NULL,
  PRIMARY KEY (`Restaurant_restname`, `stime`, `etime`),
  INDEX `fk_Thursday_Restaurant1_idx` (`Restaurant_restname` ASC),
  CONSTRAINT `fk_Thursday_Restaurant1`
    FOREIGN KEY (`Restaurant_restname`)
    REFERENCES `HappyApp`.`Restaurant` (`restname`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HappyApp`.`Friday`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HappyApp`.`Friday` ;

CREATE TABLE IF NOT EXISTS `HappyApp`.`Friday` (
  `Restaurant_restname` VARCHAR(45) NOT NULL,
  `stime` DECIMAL(3,1) NOT NULL,
  `etime` DECIMAL(3,1) NOT NULL,
  `food` VARCHAR(255) NULL,
  `drink` VARCHAR(255) NULL,
  PRIMARY KEY (`Restaurant_restname`, `stime`, `etime`),
  INDEX `fk_Friday_Restaurant1_idx` (`Restaurant_restname` ASC),
  CONSTRAINT `fk_Friday_Restaurant1`
    FOREIGN KEY (`Restaurant_restname`)
    REFERENCES `HappyApp`.`Restaurant` (`restname`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HappyApp`.`Saturday`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HappyApp`.`Saturday` ;

CREATE TABLE IF NOT EXISTS `HappyApp`.`Saturday` (
  `Restaurant_restname` VARCHAR(45) NOT NULL,
  `stime` DECIMAL(3,1) NOT NULL,
  `etime` DECIMAL(3,1) NOT NULL,
  `food` VARCHAR(255) NULL,
  `drink` VARCHAR(255) NULL,
  PRIMARY KEY (`Restaurant_restname`, `stime`, `etime`),
  INDEX `fk_Saturday_Restaurant1_idx` (`Restaurant_restname` ASC),
  CONSTRAINT `fk_Saturday_Restaurant1`
    FOREIGN KEY (`Restaurant_restname`)
    REFERENCES `HappyApp`.`Restaurant` (`restname`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HappyApp`.`Sunday`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HappyApp`.`Sunday` ;

CREATE TABLE IF NOT EXISTS `HappyApp`.`Sunday` (
  `Restaurant_restname` VARCHAR(45) NOT NULL,
  `stime` DECIMAL(3,1) NOT NULL,
  `etime` DECIMAL(3,1) NOT NULL,
  `food` VARCHAR(255) NULL,
  `drink` VARCHAR(255) NULL,
  PRIMARY KEY (`Restaurant_restname`, `stime`, `etime`),
  INDEX `fk_Sunday_Restaurant1_idx` (`Restaurant_restname` ASC),
  CONSTRAINT `fk_Sunday_Restaurant1`
    FOREIGN KEY (`Restaurant_restname`)
    REFERENCES `HappyApp`.`Restaurant` (`restname`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
