-- MySQL Script generated by MySQL Workbench
-- Thu Oct  1 13:08:14 2015
-- Model: HappyApp   Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema HappyApp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema HappyApp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `HappyApp` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `HappyApp` ;

-- -----------------------------------------------------
-- Table `HappyApp`.`Restaurant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HappyApp`.`Restaurant` ;

CREATE TABLE IF NOT EXISTS `HappyApp`.`Restaurant` (
  `restId` INT NOT NULL COMMENT '',
  `restname` VARCHAR(45) NOT NULL COMMENT '',
  `Address` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`restId`, `restname`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HappyApp`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HappyApp`.`User` ;

CREATE TABLE IF NOT EXISTS `HappyApp`.`User` (
  `curtime` TIME NOT NULL COMMENT '',
  `curday` VARCHAR(9) NULL COMMENT '',
  PRIMARY KEY (`curtime`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HappyApp`.`Monday`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HappyApp`.`Monday` ;

CREATE TABLE IF NOT EXISTS `HappyApp`.`Monday` (
  `stime` TIME NOT NULL COMMENT '',
  `etime` TIME NOT NULL COMMENT '',
  `Restaurant_restId` INT NOT NULL COMMENT '',
  `food` VARCHAR(255) NULL COMMENT '',
  `drink` VARCHAR(255) NULL COMMENT '',
  PRIMARY KEY (`stime`, `etime`, `Restaurant_restId`)  COMMENT '',
  INDEX `fk_Monday_Restaurant_idx` (`Restaurant_restId` ASC)  COMMENT '',
  CONSTRAINT `fk_Monday_Restaurant`
    FOREIGN KEY (`Restaurant_restId`)
    REFERENCES `HappyApp`.`Restaurant` (`restId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HappyApp`.`Tuesday`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HappyApp`.`Tuesday` ;

CREATE TABLE IF NOT EXISTS `HappyApp`.`Tuesday` (
  `stime` TIME NOT NULL COMMENT '',
  `etime` TIME NOT NULL COMMENT '',
  `Restaurant_restId` INT NOT NULL COMMENT '',
  `food` VARCHAR(255) NULL COMMENT '',
  `drink` VARCHAR(255) NULL COMMENT '',
  PRIMARY KEY (`stime`, `etime`, `Restaurant_restId`)  COMMENT '',
  INDEX `fk_Monday_Restaurant_idx` (`Restaurant_restId` ASC)  COMMENT '',
  CONSTRAINT `fk_Monday_Restaurant0`
    FOREIGN KEY (`Restaurant_restId`)
    REFERENCES `HappyApp`.`Restaurant` (`restId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HappyApp`.`Wednesday`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HappyApp`.`Wednesday` ;

CREATE TABLE IF NOT EXISTS `HappyApp`.`Wednesday` (
  `stime` TIME NOT NULL COMMENT '',
  `etime` TIME NOT NULL COMMENT '',
  `Restaurant_restId` INT NOT NULL COMMENT '',
  `food` VARCHAR(255) NULL COMMENT '',
  `drink` VARCHAR(255) NULL COMMENT '',
  PRIMARY KEY (`stime`, `etime`, `Restaurant_restId`)  COMMENT '',
  INDEX `fk_Monday_Restaurant_idx` (`Restaurant_restId` ASC)  COMMENT '',
  CONSTRAINT `fk_Monday_Restaurant1`
    FOREIGN KEY (`Restaurant_restId`)
    REFERENCES `HappyApp`.`Restaurant` (`restId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HappyApp`.`Thursday`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HappyApp`.`Thursday` ;

CREATE TABLE IF NOT EXISTS `HappyApp`.`Thursday` (
  `stime` TIME NOT NULL COMMENT '',
  `etime` TIME NOT NULL COMMENT '',
  `Restaurant_restId` INT NOT NULL COMMENT '',
  `food` VARCHAR(255) NULL COMMENT '',
  `drink` VARCHAR(255) NULL COMMENT '',
  PRIMARY KEY (`stime`, `etime`, `Restaurant_restId`)  COMMENT '',
  INDEX `fk_Monday_Restaurant_idx` (`Restaurant_restId` ASC)  COMMENT '',
  CONSTRAINT `fk_Monday_Restaurant2`
    FOREIGN KEY (`Restaurant_restId`)
    REFERENCES `HappyApp`.`Restaurant` (`restId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HappyApp`.`Friday`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HappyApp`.`Friday` ;

CREATE TABLE IF NOT EXISTS `HappyApp`.`Friday` (
  `stime` TIME NOT NULL COMMENT '',
  `etime` TIME NOT NULL COMMENT '',
  `Restaurant_restId` INT NOT NULL COMMENT '',
  `food` VARCHAR(255) NULL COMMENT '',
  `drink` VARCHAR(255) NULL COMMENT '',
  PRIMARY KEY (`stime`, `etime`, `Restaurant_restId`)  COMMENT '',
  INDEX `fk_Monday_Restaurant_idx` (`Restaurant_restId` ASC)  COMMENT '',
  CONSTRAINT `fk_Monday_Restaurant3`
    FOREIGN KEY (`Restaurant_restId`)
    REFERENCES `HappyApp`.`Restaurant` (`restId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HappyApp`.`Saturday`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HappyApp`.`Saturday` ;

CREATE TABLE IF NOT EXISTS `HappyApp`.`Saturday` (
  `stime` TIME NOT NULL COMMENT '',
  `etime` TIME NOT NULL COMMENT '',
  `Restaurant_restId` INT NOT NULL COMMENT '',
  `food` VARCHAR(255) NULL COMMENT '',
  `drink` VARCHAR(255) NULL COMMENT '',
  PRIMARY KEY (`stime`, `etime`, `Restaurant_restId`)  COMMENT '',
  INDEX `fk_Monday_Restaurant_idx` (`Restaurant_restId` ASC)  COMMENT '',
  CONSTRAINT `fk_Monday_Restaurant4`
    FOREIGN KEY (`Restaurant_restId`)
    REFERENCES `HappyApp`.`Restaurant` (`restId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HappyApp`.`Sunday`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HappyApp`.`Sunday` ;

CREATE TABLE IF NOT EXISTS `HappyApp`.`Sunday` (
  `stime` TIME NOT NULL COMMENT '',
  `etime` TIME NOT NULL COMMENT '',
  `Restaurant_restId` INT NOT NULL COMMENT '',
  `food` VARCHAR(255) NULL COMMENT '',
  `drink` VARCHAR(255) NULL COMMENT '',
  PRIMARY KEY (`stime`, `etime`, `Restaurant_restId`)  COMMENT '',
  INDEX `fk_Monday_Restaurant_idx` (`Restaurant_restId` ASC)  COMMENT '',
  CONSTRAINT `fk_Monday_Restaurant5`
    FOREIGN KEY (`Restaurant_restId`)
    REFERENCES `HappyApp`.`Restaurant` (`restId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
