-- MySQL Script generated by MySQL Workbench
-- Sun Oct 11 17:09:43 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Restaurant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Restaurant` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Restaurant` (
  `restname` VARCHAR(45) NOT NULL COMMENT '',
  `Address` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`restname`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`User` ;

CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `curtime` TIME NOT NULL COMMENT '',
  `curday` VARCHAR(9) NULL COMMENT '',
  PRIMARY KEY (`curtime`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Monday`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Monday` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Monday` (
  `stime` TIME NOT NULL COMMENT '',
  `etime` TIME NOT NULL COMMENT '',
  `food` VARCHAR(255) NULL COMMENT '',
  `drink` VARCHAR(255) NULL COMMENT '',
  `Restaurant_restname` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`stime`, `etime`, `Restaurant_restname`)  COMMENT '',
  INDEX `fk_Monday_Restaurant_idx` (`Restaurant_restname` ASC)  COMMENT '',
  CONSTRAINT `fk_Monday_Restaurant`
    FOREIGN KEY (`Restaurant_restname`)
    REFERENCES `mydb`.`Restaurant` (`restname`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tuesday`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Tuesday` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Tuesday` (
  `stime` TIME NOT NULL COMMENT '',
  `etime` TIME NOT NULL COMMENT '',
  `food` VARCHAR(255) NULL COMMENT '',
  `drink` VARCHAR(255) NULL COMMENT '',
  `Restaurant_restname` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`stime`, `etime`, `Restaurant_restname`)  COMMENT '',
  INDEX `fk_Tuesday_Restaurant1_idx` (`Restaurant_restname` ASC)  COMMENT '',
  CONSTRAINT `fk_Tuesday_Restaurant1`
    FOREIGN KEY (`Restaurant_restname`)
    REFERENCES `mydb`.`Restaurant` (`restname`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Wednesday`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Wednesday` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Wednesday` (
  `stime` TIME NOT NULL COMMENT '',
  `etime` TIME NOT NULL COMMENT '',
  `food` VARCHAR(255) NULL COMMENT '',
  `drink` VARCHAR(255) NULL COMMENT '',
  `Restaurant_restname` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`stime`, `etime`, `Restaurant_restname`)  COMMENT '',
  INDEX `fk_Wednesday_Restaurant1_idx` (`Restaurant_restname` ASC)  COMMENT '',
  CONSTRAINT `fk_Wednesday_Restaurant1`
    FOREIGN KEY (`Restaurant_restname`)
    REFERENCES `mydb`.`Restaurant` (`restname`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Thursday`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Thursday` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Thursday` (
  `stime` TIME NOT NULL COMMENT '',
  `etime` TIME NOT NULL COMMENT '',
  `food` VARCHAR(255) NULL COMMENT '',
  `drink` VARCHAR(255) NULL COMMENT '',
  `Restaurant_restname` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`stime`, `etime`, `Restaurant_restname`)  COMMENT '',
  INDEX `fk_Thursday_Restaurant1_idx` (`Restaurant_restname` ASC)  COMMENT '',
  CONSTRAINT `fk_Thursday_Restaurant1`
    FOREIGN KEY (`Restaurant_restname`)
    REFERENCES `mydb`.`Restaurant` (`restname`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Friday`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Friday` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Friday` (
  `stime` TIME NOT NULL COMMENT '',
  `etime` TIME NOT NULL COMMENT '',
  `food` VARCHAR(255) NULL COMMENT '',
  `drink` VARCHAR(255) NULL COMMENT '',
  `Restaurant_restname` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`stime`, `etime`, `Restaurant_restname`)  COMMENT '',
  INDEX `fk_Friday_Restaurant1_idx` (`Restaurant_restname` ASC)  COMMENT '',
  CONSTRAINT `fk_Friday_Restaurant1`
    FOREIGN KEY (`Restaurant_restname`)
    REFERENCES `mydb`.`Restaurant` (`restname`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Saturday`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Saturday` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Saturday` (
  `stime` TIME NOT NULL COMMENT '',
  `etime` TIME NOT NULL COMMENT '',
  `food` VARCHAR(255) NULL COMMENT '',
  `drink` VARCHAR(255) NULL COMMENT '',
  `Restaurant_restname` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`stime`, `etime`, `Restaurant_restname`)  COMMENT '',
  INDEX `fk_Saturday_Restaurant1_idx` (`Restaurant_restname` ASC)  COMMENT '',
  CONSTRAINT `fk_Saturday_Restaurant1`
    FOREIGN KEY (`Restaurant_restname`)
    REFERENCES `mydb`.`Restaurant` (`restname`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sunday`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Sunday` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Sunday` (
  `stime` TIME NOT NULL COMMENT '',
  `etime` TIME NOT NULL COMMENT '',
  `food` VARCHAR(255) NULL COMMENT '',
  `drink` VARCHAR(255) NULL COMMENT '',
  `Restaurant_restname` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`stime`, `etime`, `Restaurant_restname`)  COMMENT '',
  INDEX `fk_Sunday_Restaurant1_idx` (`Restaurant_restname` ASC)  COMMENT '',
  CONSTRAINT `fk_Sunday_Restaurant1`
    FOREIGN KEY (`Restaurant_restname`)
    REFERENCES `mydb`.`Restaurant` (`restname`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
